# Generated by Django 4.2.7 on 2023-11-16 02:17

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0002_answer"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuestionFeedback",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "feedback",
                    models.IntegerField(
                        choices=[(1, "good"), (0, "normal"), (-1, "bad")]
                    ),
                ),
                (
                    "question",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="questions.question",
                    ),
                ),
            ],
            options={
                "verbose_name": "질문 피드백",
                "db_table": "question_feedbacks",
            },
        ),
    ]
