# Generated by Django 4.2.7 on 2023-11-17 04:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0003_questionfeedback"),
    ]

    operations = [
        migrations.CreateModel(
            name="AI",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "type",
                    models.CharField(
                        choices=[("sara", "Sara"), ("mara", "Mara")], max_length=4
                    ),
                ),
                ("instruction", models.TextField()),
            ],
            options={
                "verbose_name": "AI",
                "db_table": "ai",
            },
        ),
    ]
