# Generated by Django 4.2.7 on 2023-11-28 00:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0005_question_hidden"),
    ]

    operations = [
        migrations.AddField(
            model_name="answer",
            name="checked",
            field=models.BooleanField(default=False),
        ),
    ]
