# Generated by Django 4.2.7 on 2024-07-15 12:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("questions", "0008_question_comment_count_question_like_count_like_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="ai",
            name="language",
            field=models.CharField(
                choices=[("KO", "Ko"), ("JA", "Ja"), ("EN", "En")],
                default="KO",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="language",
            field=models.CharField(
                choices=[("KO", "Ko"), ("JA", "Ja"), ("EN", "En")],
                default="KO",
                max_length=4,
            ),
        ),
    ]
