version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:   # db 서비스가 시작된 후에 api 서비스를 시작하도록 설정
      - db
    env_file:
      - .env
    networks:
      - sara
  service:
    build:
      context: .
      dockerfile: Dockerfile.service
    depends_on:
      - api
      - db
    env_file:
      - .env
    networks:
      - sara
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env
    networks:
      - sara

volumes:
  postgres_data:

networks:
  sara:
    driver: bridge
    external: true
    internal: true
