version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:   # db 서비스가 시작된 후에 api 서비스를 시작하도록 설정
      - db
    environment:
      - ENV=PROD
      - DB_HOST=db
      - DB_PORT=5432
      - DB_NAME=sara_db
      - DB_USER=sara
      - DB_PASSWORD=Sara123!
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=sara
      - POSTGRES_PASSWORD=Sara123!
      - POSTGRES_DB=sara_db

volumes:
  postgres_data:
