version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:   # db 서비스가 시작된 후에 api 서비스를 시작하도록 설정
      - db
    env_file:
      - .env
  db:
    image: postgres:16
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    env_file:
      - .env

volumes:
  postgres_data:
