# Generated by Django 4.2.7 on 2023-11-30 15:04

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("cs", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Feedback",
        ),
    ]
