# Generated by Django 4.2.7 on 2024-06-27 14:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("coupang", "Coupang"), ("aliexpress", "Aliexpress")],
                default="coupang",
                max_length=30,
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
