# Generated by Django 4.2.7 on 2024-07-14 07:06

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0002_category_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="category",
            name="type",
            field=models.CharField(
                choices=[("coupang", "Coupang"), ("aliexpress", "Aliexpress")],
                default="coupang",
                max_length=50,
            ),
        ),
    ]
