# Generated by Django 4.2.7 on 2024-11-24 06:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0003_alter_category_code_alter_category_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="language",
            field=models.CharField(
                choices=[("KO", "Ko"), ("JA", "Ja"), ("EN", "En")],
                default="KO",
                max_length=4,
            ),
        ),
    ]
