# Generated by Django 4.2.7 on 2024-11-24 06:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("shop", "0004_category_language"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="code",
            field=models.CharField(max_length=50),
        ),
    ]
